name: main
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./timer
          recurse: true
          output_dir: ./source
        
    
