name: doc

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
          check-latest: true
      - run: npm install
      - name: JSDoc Action
        uses: andstor/jsdoc-action@v1.2.0
        with:
          source_dir: ./timer
          recurse: true
          output_dir: ./source
        
    
