name: Lint

on:
  pull_request:
    branches: main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
      # Install your linters here
      - name: Install ESLint
        working-directory: ./timer
        run: npm install --save-dev eslint-config-standard eslint-plugin-promise eslint-plugin-import eslint-plugin-node
    
      - name: install stylelint
        working-directory: ./timer
        run: npm install --save-dev stylelint stylelint-config-standard
      
      - name: ESLint
        working-directory: ./timer
        run: npx eslint --init
      
      - name: Run ESLint
        working-directory: ./timer
        run: npx eslint "./*.js"
        
      - name: run stylelint
        working-directory: ./timer
        run: npx stylelint "./css/*.css"


