name: test

on:
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Install jest
        working-directory: ./timer
        run: npm install --save-dev jest
      - name: Run jest
        working-directory: ./timer
        run: npm test
      - name: run cypress tests
        working-directory: ./timer
        run: npm run cypress
      - name: add files
        run: git add .
      - name: Commit files
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Add changes" -a
          git push

