name: test

on:
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install jest
        working-directory: ./timer
        run: npm install --save-dev jest
      - name: Run jest
        working-directory: ./timer
        run: npm test
      - name: run cypress tests
        working-directory: ./timer
        run: npx cypress run --spec './cypress/integration/E2E'

