name: test

on:
  pull_request:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:      
      - name: Checkout code
        uses: actions/checkout@v2
      - name: change directory to timer
        run: cd timer
      - name: Install jest
        run: npm install --save-dev jest
      - name: Run jest
        run: npm test
